name: Dispatch Handler

on:
  repository_dispatch:
    types:
      - ci

jobs:
  dispatcher:
    name: Dispatched Event Handler
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Payload params
        run: |
          echo "Ref: ${{ github.event.client_payload.ref }}"
          echo "Commit: ${{ github.event.client_payload.sha }}"
