name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the source code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Node.js environment
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: 'package.json'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run all

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name && github.event.sender.login != 'dependabot[bot]' ||
      github.event_name == 'push' && !contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - name: Check out the source code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - id: action
        uses: ./
        with:
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          type: ci
          payload: '{ "ref": "${{ github.ref }}", "sha": "${{ github.sha }}" }'
